# This file is auto-generated by scripts/update-formula.sh.
class Face < Formula
  desc "Unix-style CLI for grouping, paging, and summarizing structured command output"
  homepage "https://github.com/oops-rs/face"
  url "https://github.com/oops-rs/face/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "2900066a88862765675109308042412954ccb560e8f3811b87356a6eebaeba5a"
  license "MIT"
  head "https://github.com/oops-rs/face.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", *std_cargo_args(path: "crates/face-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/face --version")
  end
end
