# This file is auto-generated by scripts/update-formula.sh.
class Face < Formula
  desc "Unix-style CLI for grouping, paging, and summarizing structured command output"
  homepage "https://github.com/oops-rs/face"
  version "0.1.0"
  url "https://github.com/oops-rs/face/releases/download/v0.1.0/face-v0.1.0-macos-arm64.tar.gz"
  sha256 "8d81c6de6deaf5061545701f1237c8bf7494bbe23cf3d75c507ccb5882e21704"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "face"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/face --version")
  end
end
