# This file is auto-generated by scripts/update-formula.sh.
class GraphaAT010 < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  url "https://github.com/oops-rs/grapha/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "fce8ba6fe3f4dd05713274593e5215bbe2b4b454e9d2961cc6ee47a095bea858"
  license "MIT"
  head "https://github.com/oops-rs/grapha.git", branch: "main"

  depends_on :macos
  depends_on "rust" => :build
  depends_on xcode: :build
  uses_from_macos "swift" => :build

  def install
    ENV["GRAPHA_SWIFT_BRIDGE_MODE"] = "required"
    ENV["GRAPHA_SWIFT_BUILD_DISABLE_SANDBOX"] = "1"

    system "cargo", "build", "-p", "grapha", "--release", "--locked"

    libexec.install "target/release/grapha"
    libexec.install "grapha-swift/swift-bridge/.build/release/libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
