# This file is auto-generated by scripts/update-formula.sh.
class Grapha < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  version "0.4.1"
  url "https://github.com/oops-rs/grapha/releases/download/v0.4.1/grapha-v0.4.1-macos-arm64.tar.gz"
  sha256 "3aa286acb4eff2059a1973a0f7e2a72348d5c5d4d6151bd32677d5c42e768302"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    libexec.install "grapha"
    libexec.install "libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
