# This file is auto-generated by scripts/update-formula.sh.
class GraphaAT011 < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  version "0.1.1"
  url "https://github.com/oops-rs/grapha/releases/download/v0.1.1/grapha-v0.1.1-macos-arm64.tar.gz"
  sha256 "5cf0ac695d20bce0298bab2d9fae07cc70ca588afe3a31d5295971519767ea37"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    libexec.install "grapha"
    libexec.install "libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
