# This file is auto-generated by scripts/update-formula.sh.
class GraphaAT040 < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  version "0.4.0"
  url "https://github.com/oops-rs/grapha/releases/download/v0.4.0/grapha-v0.4.0-macos-arm64.tar.gz"
  sha256 "1301b05981ce107d572a4d38dbfb6bf71de9de352d48a8fe14bcc2dade5f800e"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    libexec.install "grapha"
    libexec.install "libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
