# This file is auto-generated by scripts/update-formula.sh.
class GraphaAT020 < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  version "0.2.0"
  url "https://github.com/oops-rs/grapha/releases/download/v0.2.0/grapha-v0.2.0-macos-arm64.tar.gz"
  sha256 "7449a18dd910d52c699b60a8af135f73f021f41f5469f89ab1b3b811d1b5de4f"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    libexec.install "grapha"
    libexec.install "libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
