# This file is auto-generated by scripts/update-formula.sh.
class LangcodecCli < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.13.0/langcodec-v0.13.0-aarch64-apple-darwin.tar.gz"
      sha256 "d9cb21671060cc902b150dbc4dbb2008f8dfc7eed04299a20611c1b2aeb64798"
    end
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.13.0/langcodec-v0.13.0-x86_64-apple-darwin.tar.gz"
      sha256 "b358747def69aa44c092a3494e2d8d09082b7e7a2a1be03197d162268d65d6d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.13.0/langcodec-v0.13.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fb0e245c1b16465a334332c98444d2eccfd17a789a30510b7bf8d741904e4d73"
    end
  end

  def install
    bin.install "langcodec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
