# This file is auto-generated by scripts/update-formula.sh.
class LangcodecCli < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  version "0.14.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.1/langcodec-v0.14.1-aarch64-apple-darwin.tar.gz"
      sha256 "790b584b6274163ac48d8b7ac88eb2400187fe4603bc4a8db333df33f159f394"
    end
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.1/langcodec-v0.14.1-x86_64-apple-darwin.tar.gz"
      sha256 "9394aa94b6ab495a546389765721cb90e1df0fa32b4bf4cad8760f2d69768fd6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.1/langcodec-v0.14.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "685aec5428cee4b0de3ecaac0a173eb65a086d168c670d9037d4c1bec1325422"
    end
  end

  def install
    bin.install "langcodec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
