# This file is auto-generated by scripts/update-formula.sh.
class LangcodecCliAT0140 < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  version "0.14.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.0/langcodec-v0.14.0-aarch64-apple-darwin.tar.gz"
      sha256 "1e2dafc5519cc6eab0b39e1fdf6d72aed1d358e29c645bbaa8dc907895d83d27"
    end
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.0/langcodec-v0.14.0-x86_64-apple-darwin.tar.gz"
      sha256 "2d2248a81dc0d06c19018cd95a996d5349c1b8c83232234c0fd7659d1d0e8ad1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/langcodec/releases/download/v0.14.0/langcodec-v0.14.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ae54ced297afcaa96597582af32b5ea21b4106db8f76f2fef4f572b212dd7628"
    end
  end

  def install
    bin.install "langcodec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
