# This file is auto-generated by scripts/update-formula.sh.
class NumiAT022 < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.2/numi-v0.2.2-aarch64-apple-darwin.tar.gz"
      sha256 "1351d959f69b3642006e34924ba38ff32c846eb71d4dc948d9539a3fe648f2ae"
    end
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.2/numi-v0.2.2-x86_64-apple-darwin.tar.gz"
      sha256 "220eceddb4e140351bc622d52fe2d8c96a1fbb71d78249e53a6bd20c3c48524c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.2/numi-v0.2.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4fafd90d4d7c0823eca496916f097555fdd52b0aa2a59ff5bc31c72973945e23"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
