# This file is auto-generated by scripts/update-formula.sh.
class Numi < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.3/numi-v0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "e17a312acb01994052e589a230273690ac3a5aed45647207b158b96ac2eaaac7"
    end
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.3/numi-v0.2.3-x86_64-apple-darwin.tar.gz"
      sha256 "a78a2fb245c4d4b90a30f626cff02a4934e9320d253aadc804521159a133b531"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.3/numi-v0.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fdc96843f1dcead973c65a34a587aeb91d11bf567bf12bd63ca6a5157e8e143e"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
