# This file is auto-generated by scripts/update-formula.sh.
class Numi < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.5/numi-v0.2.5-aarch64-apple-darwin.tar.gz"
      sha256 "4b1271abbfab4b3786a787e51c7dfb233d2351de78fa3eb96618e06dec443978"
    end
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.5/numi-v0.2.5-x86_64-apple-darwin.tar.gz"
      sha256 "102eee7d8b5c9b7fe61cd0ef1b3b18f49621bfd917b04951f685011ff45ba58b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.5/numi-v0.2.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "147924bf28fc88d74826cead260462cbc18b099d92906a4354a5325931935f59"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
