# This file is auto-generated by scripts/update-formula.sh.
class NumiAT020 < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.0/numi-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "e229431ca78c95c01e41dff4771dcec40c4213d7dc108e03032e2de2dad860ef"
    end
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.0/numi-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "4da61be379a0b4ac5cac56460c6902ae8ee776401053989509f64e2906d0e9b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oops-rs/numi/releases/download/v0.2.0/numi-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e92e9d111b660d8a26b78de987cfa86e081a86f540907040aa10eda8f5e13309"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
