#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/update-formula.sh <formula> <tag>

Examples:
  scripts/update-formula.sh grapha v0.1.1
  scripts/update-formula.sh langcodec-cli v0.11.0
EOF
}

if [[ $# -ne 2 ]]; then
  usage >&2
  exit 1
fi

formula_name="$1"
tag="$2"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
formula_dir="${repo_root}/Formula"

class_name_for_formula() {
  local formula_basename="$1"
  local version_suffix="${2:-}"
  local base=""

  IFS='-' read -r -a parts <<< "${formula_basename}"
  for part in "${parts[@]}"; do
    base+="${part^}"
  done

  if [[ -z "${version_suffix}" ]]; then
    printf '%s\n' "${base}"
    return
  fi

  local normalized_version
  normalized_version="$(printf '%s' "${version_suffix}" | tr -cd '[:digit:]')"
  printf '%sAT%s\n' "${base}" "${normalized_version}"
}

formula_version_from_file() {
  local file="$1"
  sed -n 's|.*archive/refs/tags/\(v[^"]*\)\.tar\.gz.*|\1|p' "${file}" | head -n 1
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

render_formula() {
  local formula_name="$1"
  local archive_sha="$2"
  local class_name="$3"
  local formula_tag="$4"

  case "${formula_name}" in
    grapha)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  url "https://github.com/oops-rs/grapha/archive/refs/tags/${formula_tag}.tar.gz"
  sha256 "${archive_sha}"
  license "MIT"
  head "https://github.com/oops-rs/grapha.git", branch: "main"

  depends_on :macos
  depends_on "rust" => :build
  depends_on xcode: :build
  uses_from_macos "swift" => :build

  def install
    ENV["GRAPHA_SWIFT_BRIDGE_MODE"] = "required"
    ENV["GRAPHA_SWIFT_BUILD_DISABLE_SANDBOX"] = "1"

    system "cargo", "build", "-p", "grapha", "--release", "--locked"

    libexec.install "target/release/grapha"
    libexec.install "grapha-swift/swift-bridge/.build/release/libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
EOF
      ;;
    langcodec-cli)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  url "https://github.com/oops-rs/langcodec/archive/refs/tags/${formula_tag}.tar.gz"
  sha256 "${archive_sha}"
  license "MIT"
  head "https://github.com/oops-rs/langcodec.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", *std_cargo_args(path: "langcodec-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
EOF
      ;;
    *)
      echo "unsupported formula: $1" >&2
      exit 1
      ;;
  esac
}

case "${formula_name}" in
  grapha) repo="oops-rs/grapha" ;;
  langcodec-cli) repo="oops-rs/langcodec" ;;
  *)
    echo "unsupported formula: ${formula_name}" >&2
    exit 1
    ;;
esac

archive_url="https://github.com/${repo}/archive/refs/tags/${tag}.tar.gz"
tmp_archive="$(mktemp)"
trap 'rm -f "${tmp_archive}"' EXIT
curl -fsSL "${archive_url}" -o "${tmp_archive}"
archive_sha="$(sha256_file "${tmp_archive}")"

latest_formula_path="${formula_dir}/${formula_name}.rb"
latest_class_name="$(class_name_for_formula "${formula_name}")"

if [[ -f "${latest_formula_path}" ]]; then
  current_tag="$(formula_version_from_file "${latest_formula_path}")"
  if [[ -n "${current_tag}" && "${current_tag}" != "${tag}" ]]; then
    versioned_formula_name="${formula_name}@${current_tag#v}"
    versioned_formula_path="${formula_dir}/${versioned_formula_name}.rb"
    versioned_class_name="$(class_name_for_formula "${formula_name}" "${current_tag#v}")"
    current_archive_url="https://github.com/${repo}/archive/refs/tags/${current_tag}.tar.gz"
    current_archive="$(mktemp)"
    curl -fsSL "${current_archive_url}" -o "${current_archive}"
    current_archive_sha="$(sha256_file "${current_archive}")"
    rm -f "${current_archive}"

    render_formula "${formula_name}" "${current_archive_sha}" "${versioned_class_name}" "${current_tag}" \
      > "${versioned_formula_path}"
  fi
fi

render_formula "${formula_name}" "${archive_sha}" "${latest_class_name}" "${tag}" \
  > "${latest_formula_path}"
