#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/update-formula.sh <formula> <tag>

Examples:
  scripts/update-formula.sh grapha v0.1.1
  scripts/update-formula.sh langcodec-cli v0.11.0
  scripts/update-formula.sh numi v0.1.0
EOF
}

if [[ $# -ne 2 ]]; then
  usage >&2
  exit 1
fi

formula_name="$1"
tag="$2"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
formula_dir="${repo_root}/Formula"

class_name_for_formula() {
  local formula_basename="$1"
  local version_suffix="${2:-}"
  local base=""

  IFS='-' read -r -a parts <<< "${formula_basename}"
  for part in "${parts[@]}"; do
    base+="${part^}"
  done

  if [[ -z "${version_suffix}" ]]; then
    printf '%s\n' "${base}"
    return
  fi

  local normalized_version
  normalized_version="$(printf '%s' "${version_suffix}" | tr -cd '[:digit:]')"
  printf '%sAT%s\n' "${base}" "${normalized_version}"
}

formula_version_from_file() {
  local file="$1"
  local explicit_version=""

  explicit_version="$(sed -n 's|^[[:space:]]*version "\([^"]*\)".*|v\1|p' "${file}" | head -n 1)"
  if [[ -n "${explicit_version}" ]]; then
    printf '%s\n' "${explicit_version}"
    return
  fi

  sed -n 's|.*archive/refs/tags/\(v[^"]*\)\.tar\.gz.*|\1|p' "${file}" | head -n 1
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

download_sha256() {
  local url="$1"
  local tmp_file
  tmp_file="$(mktemp)"
  curl -fsSL "${url}" -o "${tmp_file}"
  sha256_file "${tmp_file}"
  rm -f "${tmp_file}"
}

numi_asset_filename() {
  local tag="$1"
  local target="$2"
  printf 'numi-%s-%s.tar.gz\n' "${tag}" "${target}"
}

numi_asset_url() {
  local repo="$1"
  local tag="$2"
  local target="$3"
  printf 'https://github.com/%s/releases/download/%s/%s\n' \
    "${repo}" "${tag}" "$(numi_asset_filename "${tag}" "${target}")"
}

render_formula() {
  local formula_name="$1"
  local archive_sha="$2"
  local class_name="$3"
  local formula_tag="$4"
  local numi_macos_arm_sha="${5:-}"
  local numi_macos_x86_sha="${6:-}"
  local numi_linux_x86_sha="${7:-}"

  case "${formula_name}" in
    grapha)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  url "https://github.com/oops-rs/grapha/archive/refs/tags/${formula_tag}.tar.gz"
  sha256 "${archive_sha}"
  license "MIT"
  head "https://github.com/oops-rs/grapha.git", branch: "main"

  depends_on :macos
  depends_on "rust" => :build
  depends_on xcode: :build
  uses_from_macos "swift" => :build

  def install
    ENV["GRAPHA_SWIFT_BRIDGE_MODE"] = "required"
    ENV["GRAPHA_SWIFT_BUILD_DISABLE_SANDBOX"] = "1"

    system "cargo", "build", "-p", "grapha", "--release", "--locked"

    libexec.install "target/release/grapha"
    libexec.install "grapha-swift/swift-bridge/.build/release/libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
EOF
      ;;
    langcodec-cli)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  url "https://github.com/oops-rs/langcodec/archive/refs/tags/${formula_tag}.tar.gz"
  sha256 "${archive_sha}"
  license "MIT"
  head "https://github.com/oops-rs/langcodec.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", *std_cargo_args(path: "langcodec-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
EOF
      ;;
    numi)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "${formula_tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(numi_asset_url "oops-rs/numi" "${formula_tag}" "aarch64-apple-darwin")"
      sha256 "${numi_macos_arm_sha}"
    end
    on_intel do
      url "$(numi_asset_url "oops-rs/numi" "${formula_tag}" "x86_64-apple-darwin")"
      sha256 "${numi_macos_x86_sha}"
    end
  end

  on_linux do
    on_intel do
      url "$(numi_asset_url "oops-rs/numi" "${formula_tag}" "x86_64-unknown-linux-gnu")"
      sha256 "${numi_linux_x86_sha}"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
EOF
      ;;
    *)
      echo "unsupported formula: $1" >&2
      exit 1
      ;;
  esac
}

case "${formula_name}" in
  grapha) repo="oops-rs/grapha" ;;
  langcodec-cli) repo="oops-rs/langcodec" ;;
  numi) repo="oops-rs/numi" ;;
  *)
    echo "unsupported formula: ${formula_name}" >&2
    exit 1
    ;;
esac

archive_sha=""
numi_macos_arm_sha=""
numi_macos_x86_sha=""
numi_linux_x86_sha=""

if [[ "${formula_name}" == "numi" ]]; then
  numi_macos_arm_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${tag}" "aarch64-apple-darwin")")"
  numi_macos_x86_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${tag}" "x86_64-apple-darwin")")"
  numi_linux_x86_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${tag}" "x86_64-unknown-linux-gnu")")"
else
  archive_url="https://github.com/${repo}/archive/refs/tags/${tag}.tar.gz"
  tmp_archive="$(mktemp)"
  trap 'rm -f "${tmp_archive}"' EXIT
  curl -fsSL "${archive_url}" -o "${tmp_archive}"
  archive_sha="$(sha256_file "${tmp_archive}")"
fi

latest_formula_path="${formula_dir}/${formula_name}.rb"
latest_class_name="$(class_name_for_formula "${formula_name}")"

if [[ -f "${latest_formula_path}" ]]; then
  current_tag="$(formula_version_from_file "${latest_formula_path}")"
  if [[ -n "${current_tag}" && "${current_tag}" != "${tag}" ]]; then
    versioned_formula_name="${formula_name}@${current_tag#v}"
    versioned_formula_path="${formula_dir}/${versioned_formula_name}.rb"
    versioned_class_name="$(class_name_for_formula "${formula_name}" "${current_tag#v}")"
    if [[ "${formula_name}" == "numi" ]]; then
      current_numi_macos_arm_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${current_tag}" "aarch64-apple-darwin")")"
      current_numi_macos_x86_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${current_tag}" "x86_64-apple-darwin")")"
      current_numi_linux_x86_sha="$(download_sha256 "$(numi_asset_url "${repo}" "${current_tag}" "x86_64-unknown-linux-gnu")")"

      render_formula "${formula_name}" "" "${versioned_class_name}" "${current_tag}" \
        "${current_numi_macos_arm_sha}" "${current_numi_macos_x86_sha}" "${current_numi_linux_x86_sha}" \
        > "${versioned_formula_path}"
    else
      current_archive_url="https://github.com/${repo}/archive/refs/tags/${current_tag}.tar.gz"
      current_archive="$(mktemp)"
      curl -fsSL "${current_archive_url}" -o "${current_archive}"
      current_archive_sha="$(sha256_file "${current_archive}")"
      rm -f "${current_archive}"

      render_formula "${formula_name}" "${current_archive_sha}" "${versioned_class_name}" "${current_tag}" \
        > "${versioned_formula_path}"
    fi
  fi
fi

if [[ "${formula_name}" == "numi" ]]; then
  render_formula "${formula_name}" "" "${latest_class_name}" "${tag}" \
    "${numi_macos_arm_sha}" "${numi_macos_x86_sha}" "${numi_linux_x86_sha}" \
    > "${latest_formula_path}"
else
  render_formula "${formula_name}" "${archive_sha}" "${latest_class_name}" "${tag}" \
    > "${latest_formula_path}"
fi
