#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/update-formula.sh <formula> <tag>
  scripts/update-formula.sh --versioned <formula> <tag>

Examples:
  scripts/update-formula.sh grapha v0.1.1
  scripts/update-formula.sh --versioned grapha v0.4.0
  scripts/update-formula.sh face v0.1.0
  scripts/update-formula.sh langcodec-cli v0.11.0
  scripts/update-formula.sh numi v0.1.0
EOF
}

write_versioned_only=0

case "${1:-}" in
  --versioned)
    write_versioned_only=1
    shift
    ;;
esac

if [[ $# -ne 2 ]]; then
  usage >&2
  exit 1
fi

formula_name="$1"
tag="$2"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
formula_dir="${repo_root}/Formula"

class_name_for_formula() {
  local formula_basename="$1"
  local version_suffix="${2:-}"
  local base=""

  IFS='-' read -r -a parts <<< "${formula_basename}"
  for part in "${parts[@]}"; do
    base+="${part^}"
  done

  if [[ -z "${version_suffix}" ]]; then
    printf '%s\n' "${base}"
    return
  fi

  local normalized_version
  normalized_version="$(printf '%s' "${version_suffix}" | tr -cd '[:digit:]')"
  printf '%sAT%s\n' "${base}" "${normalized_version}"
}

formula_version_from_file() {
  local file="$1"
  sed -n 's|^[[:space:]]*version "\([^"]*\)".*|v\1|p' "${file}" | head -n 1
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

download_sha256() {
  local url="$1"
  local tmp_file
  tmp_file="$(mktemp)"
  curl -fsSL "${url}" -o "${tmp_file}" || {
    rm -f "${tmp_file}"
    return 1
  }
  sha256_file "${tmp_file}"
  rm -f "${tmp_file}"
}

asset_filename() {
  local formula_name="$1"
  local tag="$2"
  local target="$3"

  case "${formula_name}:${target}" in
    grapha:macos-arm64)
      printf 'grapha-%s-macos-arm64.tar.gz\n' "${tag}"
      ;;
    face:macos-arm64)
      printf 'face-%s-macos-arm64.tar.gz\n' "${tag}"
      ;;
    langcodec-cli:aarch64-apple-darwin|langcodec-cli:x86_64-apple-darwin|langcodec-cli:x86_64-unknown-linux-gnu)
      printf 'langcodec-%s-%s.tar.gz\n' "${tag}" "${target}"
      ;;
    numi:aarch64-apple-darwin|numi:x86_64-apple-darwin|numi:x86_64-unknown-linux-gnu)
      printf 'numi-%s-%s.tar.gz\n' "${tag}" "${target}"
      ;;
    *)
      echo "unsupported binary asset target: ${formula_name} ${target}" >&2
      exit 1
      ;;
  esac
}

asset_url() {
  local repo="$1"
  local formula_name="$2"
  local tag="$3"
  local target="$4"
  printf 'https://github.com/%s/releases/download/%s/%s\n' \
    "${repo}" "${tag}" "$(asset_filename "${formula_name}" "${tag}" "${target}")"
}

macos_arm_sha=""
macos_x86_sha=""
linux_x86_sha=""

download_binary_shas() {
  local formula_name="$1"
  local repo="$2"
  local tag="$3"

  macos_arm_sha=""
  macos_x86_sha=""
  linux_x86_sha=""

  case "${formula_name}" in
    grapha|face)
      if ! macos_arm_sha="$(download_sha256 "$(asset_url "${repo}" "${formula_name}" "${tag}" "macos-arm64")")"; then
        return 1
      fi
      ;;
    langcodec-cli|numi)
      if ! macos_arm_sha="$(download_sha256 "$(asset_url "${repo}" "${formula_name}" "${tag}" "aarch64-apple-darwin")")"; then
        return 1
      fi
      if ! macos_x86_sha="$(download_sha256 "$(asset_url "${repo}" "${formula_name}" "${tag}" "x86_64-apple-darwin")")"; then
        return 1
      fi
      if ! linux_x86_sha="$(download_sha256 "$(asset_url "${repo}" "${formula_name}" "${tag}" "x86_64-unknown-linux-gnu")")"; then
        return 1
      fi
      ;;
    *)
      echo "unsupported formula: ${formula_name}" >&2
      exit 1
      ;;
  esac
}

render_formula() {
  local formula_name="$1"
  local class_name="$2"
  local formula_tag="$3"
  local formula_macos_arm_sha="${4:-}"
  local formula_macos_x86_sha="${5:-}"
  local formula_linux_x86_sha="${6:-}"

  case "${formula_name}" in
    grapha)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Structural code graph CLI and MCP server for Swift and Rust"
  homepage "https://github.com/oops-rs/grapha"
  version "${formula_tag#v}"
  url "$(asset_url "oops-rs/grapha" "${formula_name}" "${formula_tag}" "macos-arm64")"
  sha256 "${formula_macos_arm_sha}"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    libexec.install "grapha"
    libexec.install "libGraphaSwiftBridge.dylib"
    bin.write_env_script libexec/"grapha", GRAPHA_SWIFT_BRIDGE_PATH: libexec
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grapha --version")
  end
end
EOF
      ;;
    face)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Unix-style CLI for grouping, paging, and summarizing structured command output"
  homepage "https://github.com/oops-rs/face"
  version "${formula_tag#v}"
  url "$(asset_url "oops-rs/face" "${formula_name}" "${formula_tag}" "macos-arm64")"
  sha256 "${formula_macos_arm_sha}"
  license "MIT"

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "face"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/face --version")
  end
end
EOF
      ;;
    langcodec-cli)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "Universal CLI for converting and inspecting localization files"
  homepage "https://github.com/oops-rs/langcodec"
  version "${formula_tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(asset_url "oops-rs/langcodec" "${formula_name}" "${formula_tag}" "aarch64-apple-darwin")"
      sha256 "${formula_macos_arm_sha}"
    end
    on_intel do
      url "$(asset_url "oops-rs/langcodec" "${formula_name}" "${formula_tag}" "x86_64-apple-darwin")"
      sha256 "${formula_macos_x86_sha}"
    end
  end

  on_linux do
    on_intel do
      url "$(asset_url "oops-rs/langcodec" "${formula_name}" "${formula_tag}" "x86_64-unknown-linux-gnu")"
      sha256 "${formula_linux_x86_sha}"
    end
  end

  def install
    bin.install "langcodec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/langcodec --version")
  end
end
EOF
      ;;
    numi)
      cat <<EOF
# This file is auto-generated by scripts/update-formula.sh.
class ${class_name} < Formula
  desc "CLI for generating Swift code from Apple project resources"
  homepage "https://github.com/oops-rs/numi"
  version "${formula_tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(asset_url "oops-rs/numi" "${formula_name}" "${formula_tag}" "aarch64-apple-darwin")"
      sha256 "${formula_macos_arm_sha}"
    end
    on_intel do
      url "$(asset_url "oops-rs/numi" "${formula_name}" "${formula_tag}" "x86_64-apple-darwin")"
      sha256 "${formula_macos_x86_sha}"
    end
  end

  on_linux do
    on_intel do
      url "$(asset_url "oops-rs/numi" "${formula_name}" "${formula_tag}" "x86_64-unknown-linux-gnu")"
      sha256 "${formula_linux_x86_sha}"
    end
  end

  def install
    bin.install "numi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numi --version")
  end
end
EOF
      ;;
    *)
      echo "unsupported formula: $1" >&2
      exit 1
      ;;
  esac
}

case "${formula_name}" in
  grapha) repo="oops-rs/grapha" ;;
  face) repo="oops-rs/face" ;;
  langcodec-cli) repo="oops-rs/langcodec" ;;
  numi) repo="oops-rs/numi" ;;
  *)
    echo "unsupported formula: ${formula_name}" >&2
    exit 1
    ;;
esac

download_binary_shas "${formula_name}" "${repo}" "${tag}"
new_macos_arm_sha="${macos_arm_sha}"
new_macos_x86_sha="${macos_x86_sha}"
new_linux_x86_sha="${linux_x86_sha}"

latest_formula_path="${formula_dir}/${formula_name}.rb"
latest_class_name="$(class_name_for_formula "${formula_name}")"

if [[ "${write_versioned_only}" -eq 1 ]]; then
  versioned_formula_name="${formula_name}@${tag#v}"
  versioned_formula_path="${formula_dir}/${versioned_formula_name}.rb"
  versioned_class_name="$(class_name_for_formula "${formula_name}" "${tag#v}")"

  render_formula "${formula_name}" "${versioned_class_name}" "${tag}" \
    "${new_macos_arm_sha}" "${new_macos_x86_sha}" "${new_linux_x86_sha}" \
    > "${versioned_formula_path}"

  exit 0
fi

if [[ -f "${latest_formula_path}" ]]; then
  current_tag="$(formula_version_from_file "${latest_formula_path}")"
  if [[ -n "${current_tag}" && "${current_tag}" != "${tag}" ]]; then
    versioned_formula_name="${formula_name}@${current_tag#v}"
    versioned_formula_path="${formula_dir}/${versioned_formula_name}.rb"
    versioned_class_name="$(class_name_for_formula "${formula_name}" "${current_tag#v}")"
    if download_binary_shas "${formula_name}" "${repo}" "${current_tag}"; then
      render_formula "${formula_name}" "${versioned_class_name}" "${current_tag}" \
        "${macos_arm_sha}" "${macos_x86_sha}" "${linux_x86_sha}" \
        > "${versioned_formula_path}"
    else
      echo "warning: skipping ${versioned_formula_name}; binary release assets are unavailable" >&2
    fi
  fi
fi

render_formula "${formula_name}" "${latest_class_name}" "${tag}" \
  "${new_macos_arm_sha}" "${new_macos_x86_sha}" "${new_linux_x86_sha}" \
  > "${latest_formula_path}"
